# Generated by Django 6.0.6 on 2026-07-23 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('genero', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], max_length=1)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(blank=True)),
                ('doctor', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('en_espera', 'EN ESPERA'), ('confirmado', 'CONFIRMADO'), ('completado', 'COMPLETADO'), ('cancelado', 'CANCELADO'), ('no_asistio', 'NO ASISTIÓ')], default='en_espera', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='accounts.clinica')),
            ],
            options={
                'ordering': ('fecha', 'hora'),
                'constraints': [models.CheckConstraint(condition=models.Q(('edad__isnull', True), ('edad__lte', 120), _connector='OR'), name='cita_edad_valida')],
            },
        ),
    ]
