# Generated by Django 6.0.6 on 2026-07-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='clinica',
        ),
    ]
